import { db } from './db';
import { json, error, router } from './http';
import { requireAuth, authRoutes } from './auth';
import { analyzeBible, generatePassage } from './bible';
import { notifySubscribers, realtimeSubscriptionRoutes } from './realtime-subscribers';
interface Workspace{id:string;owner_id:string;name:string;slug:string;description?:string;created_at:string;updated_at:string}
interface Production{id:string;workspace_id:string;name:string;production_type:'live'|'offline';status:string;director_id:string;created_at:string;updated_at:string}
interface Pairing{id:string;code:string;workspace_id:string;status:string;created_at:string;expires_at:string}
interface Camera{id:string;pairing_id:string;workspace_id:string;device_id:string;name:string;location?:string;camera_type:string;resolution:string;fps:number;status:string;last_seen_at:string;created_at:string;updated_at:string}
function slugify(v:string){return v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,50)||'workspace'}
async function listOwnedWorkspaces(userId:string){const {items}=await db.list<Workspace>('workspaces',{filter:{owner_id:userId},limit:100});return items}
async function ensureDefaultWorkspace(userId:string,name:string){const existing=await listOwnedWorkspaces(userId);if(existing.length)return existing[0];const [id]=await db.add('workspaces',[{owner_id:userId,name,slug:`${slugify(name)}-${userId.slice(0,8)}`,description:'TAC Stream production workspace',created_at:new Date().toISOString(),updated_at:new Date().toISOString()}]);if(!id)throw new Error('workspace_create_failed');const [created]=await db.get<Workspace>('workspaces',[id]);return created?{...created,id}:null}
const makeCode=()=>String(Math.floor(100000+Math.random()*900000));
export const handler=router({'POST /api/bible/generate':[async({body})=>{const input=(body||{}) as {reference?:string;translation?:string};const reference=input.reference?.trim();const translation=input.translation?.trim()||'KJV';if(!reference)return error('Bible reference is required',400);try{const passage=await generatePassage(reference,translation);if(!passage.verse_text)return error('Bible response could not be verified',502);return json({passage});}catch(err){console.error('bible_generate_failed',err);return error('Bible passage generation failed. Please try again.',502);}}],
'POST /api/bible/analyze':[async({body})=>{const input=(body||{}) as {transcript?:string;translation?:string};const transcript=input.transcript?.trim();const translation=input.translation?.trim()||'KJV';if(!transcript)return error('Transcript is required',400);try{const analysis=await analyzeBible(transcript,translation);return json({analysis});}catch(err){console.error('bible_analyze_failed',err);return error('Bible analysis failed. Please try again.',502);}}],
...realtimeSubscriptionRoutes,
...authRoutes,
'GET /api/health':[async()=>json({ok:true,service:'tac-stream'})],
'GET /api/me':[requireAuth(),async({user})=>json({user})],
'GET /api/workspaces':[async({user})=>{const ownerId=user?.userId||'tac-public-director';const items=await listOwnedWorkspaces(ownerId);if(items.length)return json({workspaces:items});const created=await ensureDefaultWorkspace(ownerId,user?.name?`${user.name}'s Workspace`:'TAC Stream Workspace');return json({workspaces:[created]})}],
'POST /api/workspaces':[requireAuth(),async({user,body})=>{const input=(body||{}) as {name?:string;description?:string};if(!input.name?.trim())return error('Workspace name is required',400);const [id]=await db.add('workspaces',[{owner_id:user!.userId,name:input.name.trim(),slug:`${slugify(input.name)}-${user!.userId.slice(0,8)}-${Date.now().toString(36)}`,description:input.description||'',created_at:new Date().toISOString(),updated_at:new Date().toISOString()}]);if(!id)return error('Could not create workspace',500);const [workspace]=await db.get<Workspace>('workspaces',[id]);return json({workspace},201)}],
'POST /api/workspaces/:workspaceId/productions':[async({user,params,body})=>{const input=(body||{}) as {name?:string;production_type?:'live'|'offline'};if(!input.name?.trim())return error('Production name is required',400);const [workspace]=await db.get<Workspace>('workspaces',[params.workspaceId]);if(!workspace)return error('Workspace not found',404);const now=new Date().toISOString();const [id]=await db.add('productions',[{workspace_id:params.workspaceId,name:input.name.trim(),production_type:input.production_type==='offline'?'offline':'live',status:'setup',director_id:user?.userId||'tac-public-director',created_at:now,updated_at:now}]);if(!id)return error('Could not create production',500);const [production]=await db.get<Production>('productions',[id]);return json({production},201)}],
'POST /api/pairings/create':[async()=>{const workspace=await ensureDefaultWorkspace('tac-public-director','TAC Stream');const now=Date.now();const record={code:makeCode(),workspace_id:workspace.id,status:'waiting',created_at:new Date(now).toISOString(),expires_at:new Date(now+10*60*1000).toISOString()};const [id]=await db.add('camera_pairings',[record]);if(!id)return error('Could not create pairing',500);return json({pairing:{...record,id}},201)}],
'POST /api/pairings/:code/join':[async({params,body})=>{const {items}=await db.list<Pairing>('camera_pairings',{filter:{code:params.code},limit:50});const pairing=items[0];if(!pairing||Date.parse(pairing.expires_at)<Date.now())return error('Pairing code expired or invalid',404);const input=(body||{}) as {device_id?:string;name?:string;location?:string;camera_type?:string;resolution?:string;fps?:number};if(!input.device_id)return error('Device ID is required',400);const {items:cams}=await db.list<Camera>('cameras',{filter:{pairing_id:pairing.id,device_id:input.device_id},limit:50});const now=new Date().toISOString();let camera=cams[0];if(camera){const [ok]=await db.update('cameras',[{id:camera.id,record:{...camera,name:input.name||camera.name,location:input.location||camera.location,camera_type:input.camera_type||camera.camera_type,resolution:input.resolution||camera.resolution,fps:input.fps||camera.fps,status:'online',last_seen_at:now,updated_at:now}}]);if(!ok)return error('Could not update camera',500);[camera]=await db.get<Camera>('cameras',[camera.id])}else{const [id]=await db.add('cameras',[{pairing_id:pairing.id,workspace_id:pairing.workspace_id,device_id:input.device_id,name:input.name||'Phone Camera',location:input.location||'Mobile',camera_type:input.camera_type||'rear',resolution:input.resolution||'1080p',fps:input.fps||30,status:'online',last_seen_at:now,created_at:now,updated_at:now}]);if(!id)return error('Could not register camera',500);[camera]=await db.get<Camera>('cameras',[id])}await db.update('camera_pairings',[{id:pairing.id,record:{...pairing,status:'connected'}}]);return json({camera})}],
'GET /api/pairings/:code/cameras':[async({params})=>{const {items}=await db.list<Pairing>('camera_pairings',{filter:{code:params.code},limit:50});const pairing=items[0];if(!pairing)return error('Pairing not found',404);const {items:cameras}=await db.list<Camera>('cameras',{filter:{pairing_id:pairing.id},limit:50});return json({cameras})}],
'POST /api/cameras/:cameraId/heartbeat':[async({params})=>{const [camera]=await db.get<Camera>('cameras',[params.cameraId]);if(!camera)return error('Camera not found',404);const now=new Date().toISOString();const [ok]=await db.update('cameras',[{id:camera.id,record:{...camera,status:'online',last_seen_at:now,updated_at:now}}]);if(!ok)return error('Heartbeat failed',500);return json({ok:true,last_seen_at:now})}],
'PUT /api/cameras/:cameraId':[async({params,body})=>{try{const [camera]=await db.get<Camera>('cameras',[params.cameraId]);if(!camera)return error('Camera not found',404);const input=(body||{}) as {name?:string;location?:string;resolution?:string;fps?:number};const record={...camera,name:typeof input.name==='string'&&input.name.trim()?input.name.trim():camera.name,location:typeof input.location==='string'&&input.location.trim()?input.location.trim():(camera.location||'Mobile'),resolution:typeof input.resolution==='string'&&input.resolution.trim()?input.resolution.trim():camera.resolution,fps:Number.isFinite(Number(input.fps))&&Number(input.fps)>0?Number(input.fps):camera.fps,updated_at:new Date().toISOString()};const [ok]=await db.update('cameras',[{id:params.cameraId,record}]);if(!ok)return error('Could not update camera',500);const [saved]=await db.get<Camera>('cameras',[params.cameraId]);return json({camera:saved?{...saved,id:params.cameraId}:{...record,id:params.cameraId}})}catch(err){console.error('camera_update_failed',err);return error('Could not update camera',500)}}],
'POST /api/webrtc/signal':[async({body})=>{const input=(body||{}) as {pairing_id?:string;from?:string;to?:string;type?:string;camera_id?:string;sdp?:unknown};if(!input.pairing_id||!input.from||!input.to||!input.type)return error('pairing_id, from, to and type are required',400);await notifySubscribers('pairing',input.pairing_id,{signal:input}) ;return json({ok:true})}]
});
